### ISSUE TITLE
the slack.go SetDebug(debug bool) is removed

### ISSUE THREAD

**Issue by super-organism** [micro/go-bot#1]
![image](https://user-images.githubusercontent.com/29723072/46594173-ce394400-cb03-11e8-8605-9662f677189a.png)
the SetDebug(debug bool)   is removed   

the cmd "go get -u github.com/micro/micro" has error "go-bot/input/slack/slack.go:113:5: api.SetDebug undefined (type *slack.Client has no field or method SetDebug)"

**Comment by asim** [comment]
Fixed thanks

**Comment by super-organism** [comment]
haha .  i will pr for this . but you have fixed it
